# Generated by Django 2.2.9 on 2020-01-01 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(blank=True, null=True, upload_to='', verbose_name='商品缩略图')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='价格')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='商品详情')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('lease_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='租用价格')),
                ('lease_deposit', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='租用押金')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='用户名')),
                ('mobile', models.CharField(max_length=24, verbose_name='注册手机号码')),
                ('bank', models.CharField(max_length=24, verbose_name='开户行')),
                ('account', models.CharField(max_length=24, verbose_name='账号')),
                ('vx', models.CharField(max_length=24, verbose_name='微信')),
                ('alipay', models.CharField(max_length=24, verbose_name='支付宝')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('re_moble', models.CharField(max_length=24, verbose_name='推荐人手机号码')),
                ('wle_income', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='批发收益')),
                ('retail_income', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='零售收益')),
                ('token', models.CharField(max_length=64, verbose_name='登录token')),
                ('refresh_token', models.CharField(max_length=64, verbose_name='刷新token')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_login_time', models.DateTimeField(auto_now_add=True, verbose_name='最后登录时间2')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='积分')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(max_length=64, verbose_name='订单号')),
                ('type_buy', models.CharField(max_length=16, verbose_name='购买方式')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('shipping_status', models.SmallIntegerField(default=0, verbose_name='发货状态')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pay_status', models.SmallIntegerField(default=0, verbose_name='订单状态')),
                ('pay_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pay_way', models.CharField(max_length=64, verbose_name='订单号')),
                ('pay_get_raw', models.TextField(verbose_name='支付信息')),
                ('pay_raw', models.TextField(verbose_name='支付信息')),
                ('status', models.SmallIntegerField(default=0, verbose_name='收货状态')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_id', to='index.User', verbose_name='商户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User', verbose_name='用户')),
            ],
        ),
    ]
